zadanie rekrutacyjne
rstit/luncher-api pull request #9
Opened 2018-08-17 14:03 UTC by kswiatek92

2018-08-20 06:36 UTC, Litery commented
Pyflakes errors are not fixed.

2018-08-20 08:42 UTC, kswiatek92 commented
@Litery pyflakes errors fixed

2018-08-21 08:01 UTC, Litery requested changes

2018-08-21 08:01 UTC, Litery commented on luncher/auth/views.py
> +            s = TimestampSigner(current_app.config.get('SECRET_KEY'))
Why are you creating a new signer upon every request?

2018-08-21 08:01 UTC, Litery commented on luncher/meals/views.py
> +        meal_name = request.json.get('name')
Use marshmallow's load functionality.

2018-08-21 12:49 UTC, kswiatek92 commented on luncher/auth/views.py
> +            s = TimestampSigner(current_app.config.get('SECRET_KEY'))
done

2018-08-21 12:50 UTC, kswiatek92 commented on luncher/meals/views.py
> +        meal_name = request.json.get('name')
done

2026-04-22 16:21 UTC, closed without merging